# Generated by Django 3.2.4 on 2021-06-15 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eminisce', '0002_auto_20210615_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Full name of the library user.', max_length=100, verbose_name='Full name')),
                ('status', models.CharField(choices=[('CAN BORROW', 'User is allowed to borrow books'), ('CANNOT BORROW', 'User is not allowed to borrow books')], default='CAN BORROW', max_length=30)),
                ('user_type', models.CharField(choices=[('STUDENT', 'User is a student enrolled in the institution.'), ('CORPORATE MEMBER', 'User is a staff member in the institution')], default='STUDENT', max_length=30)),
                ('fingerprint', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
