# Generated by Django 3.2.4 on 2021-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0003_auto_20210615_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='fingerprint',
            field=models.BinaryField(blank=True),
        ),
    ]
