# Generated by Django 3.2.4 on 2021-06-16 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0004_alter_libraryuser_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Loan is currently active.'), ('RETURNED', 'Loan is finished, book returned.'), ('LATE', 'Loan not finished, user is late on returning book.'), ('RETURNED LATE', 'Loan finished, but book was returned past due.')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(default=datetime.datetime.today, help_text='The start date of the loan.')),
                ('due_date', models.DateField(default=datetime.datetime(2021, 7, 7, 7, 4, 43, 237966, tzinfo=utc), help_text='The due date of the loan.')),
                ('return_date', models.DateField(help_text='The actual date the book was returned and the loan finishes.', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eminisce.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eminisce.libraryuser')),
            ],
        ),
    ]
