# Generated by Django 3.2.4 on 2021-08-04 18:37

import datetime
from django.db import migrations, models
import eminisce.models.loans


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0008_auto_20210617_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='face_front',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='face_leftside',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='face_rightside',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=eminisce.models.loans.Loan.due_date_field, help_text='The due date of the loan.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The start date of the loan.'),
        ),
    ]
