# Generated by Django 3.2.4 on 2021-08-06 04:38

from django.db import migrations
import eminisce.models.libraryuser


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0009_auto_20210805_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='face_front',
            field=eminisce.models.libraryuser.FixedBinaryInputField(blank=True, default=None, editable=True, null=True, verbose_name='Face recognition'),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='face_leftside',
            field=eminisce.models.libraryuser.FixedBinaryInputField(blank=True, default=None, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='face_rightside',
            field=eminisce.models.libraryuser.FixedBinaryInputField(blank=True, default=None, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='fingerprint',
            field=eminisce.models.libraryuser.FixedBinaryInputField(blank=True, default=None, editable=True, null=True),
        ),
    ]
