# Generated by Django 3.2.4 on 2021-08-07 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0010_auto_20210806_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount in SGD.', verbose_name='Amount')),
                ('reason', models.CharField(help_text='Reason for the fine.', max_length=200, null=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('PAID', 'Fine has been settled.'), ('UNPAID', 'Fine is not yet paid.')], default='PAID', max_length=20)),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now, help_text='The issue date of the loan.')),
                ('paid_date', models.DateTimeField(help_text='The date the user has paid for this fine.', null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eminisce.libraryuser')),
            ],
        ),
    ]
