# Generated by Django 3.2.4 on 2021-08-07 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0011_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in SGD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
    ]
