# Generated by Django 3.2.4 on 2021-08-07 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0012_alter_fine_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in SGD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='status',
            field=models.CharField(choices=[('PAID', 'Fine has been settled.'), ('UNPAID', 'Fine is not yet paid.')], default='UNPAID', max_length=20),
        ),
    ]
