# Generated by Django 3.2.4 on 2021-08-07 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0014_alter_fine_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in SGD. Up to 2 decimal places.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
    ]
