# Generated by Django 3.2.4 on 2021-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eminisce', '0016_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='extended',
            field=models.BooleanField(default=False, help_text='Has the borrower requested to extend the due date?'),
        ),
    ]
